version: 2.1
orbs:
  newman: postman/newman@0.0.1
jobs:
  newman-collection-run-env-timeout:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./collection/Training.postman_collection.json
          environment: ./env/LAMP_S.postman_environment.json

