version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  build:
    newman-collection-run-env-timeout:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - run:
          name: Install jq
          command: |
            wget http://security.ubuntu.com/ubuntu/pool/main/a/apt/apt_1.6.1_amd64.deb
            dpkg -i apt_1.6.1_amd64.deb
            apt-get install jq
      - run:
          name: Convert json
          command: |
            jq -c '.Training.postman_collection | fromjson' ./collection/Training.postman_collection.json
      - newman/newman-run:
          collection: ./collection/Training.postman_collection.json
          environment: ./env/LAMP_S.postman_environment.json

